install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
- npm i
before_script:
- rm -rf public
- hugo
script:
- npm run deploy
branches:
  only:
  - master