baseURL = "https://michaelsimsoe.no"
languageCode = "no"
defaultContentLanguage = "no"
title = "michaelsimsoe.no"

[author]
  name = "Michael Krøyserth-Simsø"

images = [""]

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]